version: 2
jobs:
  build-mac:
    machine:
      xcode: "9.2"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Create application with installer
          command: npm run dist
      - store_artifacts:
          path: "dist/Shabad OS Installer.pkg"
      - store_artifacts:
          path: "dist/Shabad OS Installer.dmg"

  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Create application with installer
          command: npm run dist
      - store_artifacts:
          path: "dist/Shabad OS Installer.exe"
      - store_artifacts:
          path: "dist/Shabad OS Portable.exe"
      - add_ssh_keys:
          fingerprints:
            - "e5:71:50:86:4f:6c:3e:f6:8b:f2:d5:45:ec:f0:9a:f1"
      - deploy:
          name: Release executables on Github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Write npm token to .npmrc
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

              # Configure git
              git config --global push.default current
              # Remove .gitignore to allow the built DB to be pushed
              rm .gitignore

              # Remove data to reduce npm package size
              rm -rf data

              # Run Release script
              chmod +x release.sh
              echo "Releasing on Github"
              npm run release
            fi


workflows:
  version: 2
  build-all:
    jobs:
      - build-windows
      - build-mac