version: 2.1

# Generic build job
build: &build
  working_directory: ~/shabad-os
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install --unsafe-perm
    - run:
        name: Build application
        command: npm run build
    - run:
        name: Build binaries
        command: npm run dist -- -${PLATFORM_FLAG}
    - run: mkdir artifacts && cp dist/Shabad* artifacts
    - persist_to_workspace:
        root: ~/shabad-os
        paths:
          - node_modules
          - app/frontend/build
    - store_artifacts:
        path: artifacts
        destination: artifacts
    - add_ssh_keys:
        fingerprints:
          - "e5:71:50:86:4f:6c:3e:f6:8b:f2:d5:45:ec:f0:9a:f1"

# Generic publish job
publish: &publish
  working_directory: ~/shabad-os
  steps:
    - checkout
    - attach_workspace:
        at: ~/shabad-os
    - run:
        name: Publish application
        command: GH_TOKEN=$GITHUB_TOKEN npm run release -- -${PLATFORM_FLAG} -p always

orbs:
  win: circleci/windows@1.0.0

jobs:
  lint:
    docker:
      - image: node:10
    working_directory: ~/shabad-os
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --unsafe-perm
      - run:
          name: Run ESLint on Frontend & Backend
          command: npm run lint
  
  build-mac:
    <<: *build
    macos:
      xcode: "9.0"
    environment:
      PLATFORM_FLAG: "m"

  build-linux:
    <<: *build
    docker:
      - image: electronuserland/builder
    environment:
      USE_HARD_LINKS: false
      PLATFORM_FLAG: "l"

  build-windows:
    <<: *build
    executor:
      name: win/vs2019
      shell: bash.exe
    environment:
      USE_HARD_LINKS: false
      PLATFORM_FLAG: "w"

  publish-mac:
    <<: *publish
    macos:
      xcode: "9.0"
    environment:
      PLATFORM_FLAG: "m"

  publish-linux:
    <<: *publish
    docker:
      - image: electronuserland/builder
    environment:
      USE_HARD_LINKS: false
      PLATFORM_FLAG: "l"

  publish-windows:
    <<: *publish
    executor:
      name: win/vs2019
      shell: bash.exe
    environment:
      USE_HARD_LINKS: false
      PLATFORM_FLAG: "w"

workflows:
  version: 2
  build-desktop:
    jobs:
      - lint
      - build-windows:
          pre-steps:
            - run: npm install --global --production windows-build-tools --vs2015
          requires:
            - lint
      - publish-windows:
          pre-steps:
            - run: npm install --global --production windows-build-tools --vs2015
          requires:
            - build-windows
          filters:
            branches:
              only:
                - master
      - build-mac:
          requires:
            - lint
      - publish-mac:
          requires:
            - build-mac
          filters:
            branches:
              only:
                - master
      - build-linux:
          requires:
            - lint
      - publish-linux:
          requires:
            - build-linux
          filters:
            branches:
              only:
                - master
